language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

services:
  - couchdb
  - riak

addons:
  apt:
    packages:
      - libproj0
      - libgeos-dev
      - libgdal-dev
      - libgdal1h
      - libxslt1-dev
      - libxml2-dev
      - build-essential
      - python-dev
      - libjpeg-dev
      - zlib1g-dev
      - libfreetype6-dev
      - protobuf-compiler
      - libprotoc-dev

env:
  global:
    - MAPPROXY_TEST_COUCHDB=http://127.0.0.1:5984

    # do not load /etc/boto.cfg with Python 3 incompatible plugin
    # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
    - BOTO_CONFIG=/doesnotexist

matrix:
  allow_failures:
    - python: "2.6"
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/pip

before_install:
    - echo -n "ulimit -n 4096" | sudo tee /etc/default/riak && sudo service riak restart	# default open file limit is too low for riak

install:
    - "export MAPPROXY_TEST_RIAK_HTTP=http://localhost:8098"
    - "export MAPPROXY_TEST_RIAK_PBC=pbc://localhost:8087"
    - "pip install -r requirements-tests.txt"
    - "pip freeze"

script: nosetests mapproxy
