language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
services:
  - couchdb
  - riak
# command to install dependencies
install:
    - "if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then pip install https://github.com/Toblerity/Shapely/archive/master.zip; fi"
    - "if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then pip install --use-mirrors protobuf==2.5.0 riak==2.0.1 riak_pb==1.4.1.1; export MAPPROXY_TEST_COUCHDB=http://127.0.0.1:5984; export MAPPROXY_TEST_RIAK_PBC=pbc://localhost:8087; fi"
    - "sudo apt-get update && sudo apt-get install libproj0 libgeos-dev libgdal-dev libxslt1-dev libxml2-dev build-essential python-dev libjpeg-dev zlib1g-dev libfreetype6-dev protobuf-compiler libprotoc-dev"
    - "pip install -r requirements-tests.txt --use-mirrors"
    # Deal with issue on Travis builders re: multiprocessing.SemLock
    # see https://github.com/travis-ci/travis-cookbooks/issues/155
    - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
# command to run tests
script: nosetests mapproxy
