language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
services:
  - couchdb
# command to install dependencies
install:
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors multiprocessing; fi"
    - "if [[ $TRAVIS_PYTHON_VERSION != '2.5' ]]; then pip install requests==0.14.0; export MAPPROXY_TEST_COUCHDB=http://127.0.0.1:5984; fi"
    - "sudo apt-get install libproj0 libgeos-dev libgdal-dev libxslt1-dev libxml2-dev build-essential python-dev libjpeg-dev zlib1g-dev libfreetype6-dev"
    - "pip install -r requirements-travis.txt --use-mirrors"
# command to run tests
script: nosetests mapproxy
