language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
services:
  - couchdb
# command to install dependencies
install:
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors multiprocessing; fi"
    - "if [[ $TRAVIS_PYTHON_VERSION != '2.5' ]]; then pip install --use-mirrors requests==1.2.3; export MAPPROXY_TEST_COUCHDB=http://127.0.0.1:5984; fi"
    - "sudo apt-get update && sudo apt-get install libproj0 libgeos-dev libgdal-dev libxslt1-dev libxml2-dev build-essential python-dev libjpeg-dev zlib1g-dev libfreetype6-dev"
    - "pip install -r requirements-travis.txt --use-mirrors"
    # Deal with issue on Travis builders re: multiprocessing.SemLock
    # see https://github.com/travis-ci/travis-cookbooks/issues/155
    - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
# command to run tests
script: nosetests mapproxy
