language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
services:
  - couchdb
  - riak

addons:
  apt:
    packages:
      -libproj0
      -libgeos-dev
      -libgdal-dev
      -libgdal1h
      -libxslt1-dev
      -libxml2-dev
      -build-essential
      -python-dev
      -libjpeg-dev
      -zlib1g-dev
      -libfreetype6-dev
      -protobuf-compiler
      -libprotoc-dev

# command to install dependencies
install:
    - "if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then pip install --use-mirrors protobuf>=2.4.1 riak==2.2 riak_pb>=2.0; export MAPPROXY_TEST_COUCHDB=http://127.0.0.1:5984; export MAPPROXY_TEST_RIAK_PBC=pbc://localhost:8087; fi"
    - "export MAPPROXY_TEST_COUCHDB=http://127.0.0.1:5984"
    - "pip install -r requirements-tests.txt --use-mirrors"
# command to run tests
script: nosetests mapproxy
