services:
  tms:
  wms:
    md:
        title: MapProxy WMS Proxy
        abstract: This is the fantastic MapProxy.
        online_resource: http://mapproxy.org/
        contact:
            person: Your Name Here
            position: Technical Director
            organization: 
            address: Fakestreet 123
            city: Somewhere
            postcode: 12345
            country: Germany
            phone: +49(0)000-000000-0
            fax: +49(0)000-000000-0
            email: info@omniscale.de
        access_constraints:
            This service is intended for private and evaluation use only.
            The data is licensed as Creative Commons Attribution-Share Alike 2.0
            (http://creativecommons.org/licenses/by-sa/2.0/)
        fees: 'None'

layers:
  osm:
    title: Omniscale OSM WMS - osm.omniscale.net
    sources: [osm]

caches:
  osm:
    grids: [global_spherical, global_mercator]
    sources: [osm_wms]
  
sources:
  osm_wms:
    type: wms
    req:
      url: http://osm.omniscale.net/proxy/service?
      layers: osm

grids:
  global_spherical:
    srs: 'EPSG:4326'
    res: 'sqrt2'
  global_mercator:
    srs: 'EPSG:900913'
    res: 'sqrt2'
    